# Производственные константы
MAX_PRODUCTION_CAPACITY = 1000
MIN_QUALITY_STANDARD = 0.85
STANDARD_WORKING_HOURS_PER_DAY = 8
MAX_WORKING_HOURS_PER_WEEK = 40
STANDARD_WARRANTY_MONTHS = 12

# Технические спецификации
MIN_ENGINE_HORSEPOWER = 50
MAX_ENGINE_HORSEPOWER = 1000
VALID_ENGINE_CYLINDERS = [4, 6, 8, 12]
MIN_TRANSMISSION_GEARS = 4
MAX_TRANSMISSION_GEARS = 10
MIN_BRAKE_DISC_DIAMETER = 200
MAX_BRAKE_DISC_DIAMETER = 400
MIN_VOLTAGE = 12
MAX_VOLTAGE = 48
MIN_CHASSIS_WHEELBASE = 2000
MAX_CHASSIS_WHEELBASE = 4000
COMFORT_BASE_VALUE = 100

# Финансовые константы
STANDARD_TAX_RATE = 0.20
EMPLOYEE_SALARY_TAX_RATE = 0.13
SHIPPING_COST_PER_KG_PER_KM = 0.1
BANK_TRANSFER_FEE_AMOUNT = 1.0
CREDIT_CARD_FEE_PERCENTAGE = 0.03
STANDARD_DISCOUNT_RATE = 0.05
MATERIAL_COST_MULTIPLIER = 10
COMPLEXITY_COST_MULTIPLIER = 5
WEIGHT_COST_MULTIPLIER = 2
BASE_REPAIR_COST = 50.0

# Складские константы
MINIMUM_STOCK_LEVEL = 10
MAXIMUM_STOCK_LEVEL = 1000
CRITICAL_STOCK_RATIO_THRESHOLD = 0.2
LOW_STOCK_RATIO_THRESHOLD = 0.5
HIGH_STOCK_RATIO_THRESHOLD = 0.8
DEFAULT_WAREHOUSE_CAPACITY = 1500

# Валидационные константы
MINIMUM_NAME_LENGTH = 2
MAXIMUM_NAME_LENGTH = 100
MINIMUM_EMPLOYEE_SALARY = 0
MINIMUM_PART_WEIGHT = 0.1
MINIMUM_PARTS_FOR_ASSEMBLY = 2

# Материалы
VALID_MATERIAL_TYPES = ["steel", "aluminum", "plastic", "copper", "rubber", "composite"]

# Статусы
PRODUCTION_ORDER_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"]
TRANSACTION_STATUSES = ["PENDING", "APPROVED", "COMPLETED", "REJECTED"]
MAINTENANCE_STATUSES = ["SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED"]

# Математические константы
PERCENTAGE_MULTIPLIER = 100
ZERO_VALUE = 0
MINIMUM_POSITIVE_VALUE = 0.001
BASE_SUCCESS_PROBABILITY = 0.85
CERTIFICATION_BONUS_RATE = 0.02
OPERATOR_SKILL_BONUS = 0.03
EFFICIENCY_LOSS_PER_LOAD = 0.1
BASE_EFFICIENCY = 0.85

# Демонстрационные данные
DEMO_ENGINE_WEIGHT = 150.0
DEMO_ENGINE_HORSEPOWER = 300
DEMO_ENGINE_CYLINDERS = 6
DEMO_TRANSACTION_AMOUNT = 5000.0
DEMO_ACCOUNT_BALANCE = 10000.0
DEMO_PRODUCTION_CAPACITY = 100
DEMO_OPERATOR_SALARY = 45000.0
DEMO_PART_WEIGHT = 5.0
DEMO_PRODUCTION_QUANTITY = 5
