# Производственные константы
MAX_PRODUCTION_CAPACITY = 1000
MIN_QUALITY_STANDARD = 0.85

# Технические спецификации
MIN_ENGINE_HORSEPOWER = 50
MAX_ENGINE_HORSEPOWER = 1000
VALID_ENGINE_CYLINDERS = [4, 6, 8, 12]

# Финансовые константы
STANDARD_TAX_RATE = 0.20
EMPLOYEE_SALARY_TAX_RATE = 0.13
BANK_TRANSFER_FEE_AMOUNT = 1.0

# Складские константы
MINIMUM_STOCK_LEVEL = 10
MAXIMUM_STOCK_LEVEL = 1000

# Валидационные константы
MINIMUM_NAME_LENGTH = 2
MAXIMUM_NAME_LENGTH = 100
MINIMUM_EMPLOYEE_SALARY = 15000
MINIMUM_PART_WEIGHT = 0.1

# Статусы
PRODUCTION_ORDER_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"]
TRANSACTION_STATUSES = ["PENDING", "APPROVED", "COMPLETED", "REJECTED"]

# Математические константы
PERCENTAGE_MULTIPLIER = 100
ZERO_VALUE = 0

# Новые константы
BASE_SUCCESS_PROBABILITY = 0.85
MATERIAL_COST_MULTIPLIER = 10
BASE_REPAIR_COST = 50.0
MINIMUM_PARTS_FOR_ASSEMBLY = 2

# Демонстрационные данные
DEMO_ENGINE_WEIGHT = 150.0
DEMO_ENGINE_HORSEPOWER = 300
DEMO_ENGINE_CYLINDERS = 6
DEMO_TRANSACTION_AMOUNT = 5000.0
DEMO_ACCOUNT_BALANCE = 10000.0

# НОВЫЕ КОНСТАНТЫ (добавлены для исправления ошибок):
DEMO_ENGINE_MATERIAL = "steel"
DEMO_ENGINE_FUEL_TYPE = "gasoline"
DEMO_ENGINE_NAME = "Двигатель V6"

DEMO_PART_MATERIAL = "steel"
DEMO_PART_WEIGHT = 10.0
DEMO_PART_NAME = "Деталь"

PRODUCTION_LINE_CAPACITY = 100
WAREHOUSE_CAPACITY = 1000
STANDARD_SALARY_TAX = 0.13
MIN_PASSWORD_LENGTH = 8
STANDARD_CVV_LENGTH = 3
MIN_STRONG_PASSWORD_SCORE = 60

# ДЛЯ Engine.simulate_race()
RACE_SPEED_PER_HP = 0.1
RACE_EFFICIENCY = 0.85
MIN_RACE_DISTANCE = 0.5
MAX_RACE_DISTANCE = 50.0

# ДЛЯ Budget.check_budget_health()
BUDGET_HEALTHY_LIMIT = 70
BUDGET_WARNING_LIMIT = 85

# ДЛЯ PaymentProcessor.validatePasswordStrength()
PASSWORD_MIN_LENGTH = 8
PASSWORD_STRONG_SCORE = 60

SHIPPING_COST_PER_KG_PER_KM = 0.1
VALID_MATERIAL_TYPES = ["steel", "aluminum", "carbon", "composite", "plastic"]

# Тормозная система
BRAKE_DIAMETER_COST_FACTOR = 15
MIN_BRAKE_DISC_DIAMETER = 200
MAX_BRAKE_DISC_DIAMETER = 400
VALID_BRAKE_TYPES = ["независимая", "зависимая", "independent", "dependent"]
STANDARD_MATERIAL_COST = 500

# Составные детали
COMPOSITE_CHILD_COST_FACTOR = 10 
MAX_CHILD_PARTS_PER_COMPOSITE = 20  
